sudo: required
services:
  - docker

before_install:
  - docker build -t mayitoukou/docker-react -f Dockerfile.dev .

script:
  - docker run mayitoukou/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeantalk
  region: "eu-west-3"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-257918213745"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY" 